### ISSUE TITLE
Hardware?

### ISSUE THREAD

**Issue by ruppde** [OverTheWireOrg/advent2019-gift#1]
Hi

could you publish what hardware this is, searching for "open smart usb" shows gazillions of similar gadgets ;)

**Comment by StevenVanAcker** [comment]
the hardware is a clone of a digispark ATTiny85 development board, flashed with the latest micronucleus bootloader so that you can program it using the Arduino IDE. I plan to post some more information soon, since most people will have received their gifts by now :)

**Comment by StevenVanAcker** [comment]
the info is now in the repo :)
